FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn package

FROM eclipse-temurin:21-jre
WORKDIR /work/
COPY --from=build /app/target/quarkus-app/ /work/
EXPOSE 8080
CMD ["java", "-jar", "quarkus-run.jar"]